data:
  directory: 
  LOM_folder: train_LOM512
  SEM_folder: train_SEM512
  test_LOM_folder: test_LOM512
  test_SEM_folder: test_SEM512
  split: None

train:
  input_size: [256, 256]
  batch_size: 16
  epochs: 100000
  gen_lr: 2.e-4
  disc_lr: 2.e-4
  max_steps: 100000
  lr_decay_start: 3000
  lr_decay_factor: 0.01
  dropout: 0.001
  augmentations:
    - [RandomHorizontalFlip, {p: 0.5}]
    - [RandomVerticalFlip, {p: 0.5}]
    - [MyRotateTransform, {}]

log:
  directory: 
  display_freq: 500
  n_row_imgs: 4 # number of images per row
  log_freq: 50

pix2pix:
  lambda_recon: 50
  patch_level: 3
  adv_loss_type: LS # CE, LS
