data:
  directory: 
  LOM_folder: train_LOM512
  SEM_folder: train_SEM512
  test_LOM_folder: test_LOM512
  test_SEM_folder: test_SEM512
  split: null
  desc_checkpoint: null

train:
  input_size: [512, 512]
  batch_size: 32
  epochs: 3000
  lr: 2.e-4
  max_steps: 9000
  lr_decay_start: 3000
  lr_decay_factor: 0.01
  wt_s: 10
  augmentations:
    - [RandomHorizontalFlip, {p: 0.5}]
    - [RandomVerticalFlip, {p: 0.5}]
    - [MyRotateTransform, {}]

log:
  display_freq: 500
  n_row_imgs: 4 # number of images per row
  log_freq: 100
  directory: 
